spring:
  cloud:
    gateway:
      routes:
        - id: r1
          uri:
            http://localhost:8080/
          predicates:
            - Path= /acheteurs/**
        - id: r2
          uri:
            http://localhost:8081/
          predicates:
            - Path= /produits/**
        - id: r3
          uri:
            http://localhost:8082/
          predicates:
            - Path= /ventes/**
        - id: r4
          uri:
            http://localhost:8083/
          predicates:
            - Path= /login/**
            - Path= /users/**